### ISSUE TITLE
make_DPLR_HiPPO should be defined earlier?

### ISSUE THREAD

**Issue by ratishsp** [srush/annotated-s4#73]
Thanks for this very helpful blogpost.

```
def test_gen_dplr(L=16, N=4):
    I = np.eye(4)

    # Create a DPLR A matrix and discretize
    Lambda, P, B, _ = make_DPLR_HiPPO(N)
...
```
The function make_DPLR_HiPPO is only defined later in the post. I was wondering if that was by design?

**Comment by albertfgu** [comment]
I think it's by design. That section of the blogpost focuses on the computational aspect of working with DPLR - abstracting away precise instantiations of DPLR matrices. The `make_DPLR_HiPPO` method is called only to provide a concrete DPLR matrix for testing; a randomly generated one would have worked just as well for the purposes of this testing function.

**Comment by ratishsp** [comment]
That helps, thanks!
